# Generated by Django 4.2.11 on 2024-04-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_alter_tenant_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="room_number",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
