# Generated by Django 4.2.11 on 2024-04-22 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_room_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="aadhar_number",
            field=models.CharField(
                default=0,
                max_length=16,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(10),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenant",
            name="company_address",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
